import Japanese from './Japanese';
import CityName from '@civ-clone/core-civilization/CityName';
import { instance as cityNameRegistryInstance } from '@civ-clone/core-civilization/CityNameRegistry';

([
  'Tokyo',
  'Kanagawa',
  'Osaka',
  'Aichi',
  'Hokkaidō',
  'Fukuoka',
  'Hyōgo',
  'Kyoto',
  'Saitama',
  'Hiroshima',
  'Miyagi',
  'Chiba',
  'Niigata',
  'Shizuoka',
  'Okayama',
  'Kumamoto',
  'Kagoshima',
  'Ehime',
  'Tochigi',
  'Ōita',
  'Ishikawa',
  'Nagasaki',
  'Toyama',
  'Kagawa',
  'Gifu',
  'Nagano',
  'Wakayama',
  'Miyazaki',
  'Nara',
  'Fukushima',
  'Kōchi',
  'Gunma',
  'Akita',
  'Shiga',
  'Okinawa',
  'Mie',
  'Aomori',
  'Iwate',
  'Yamaguchi',
  'Fukui',
  'Tokushima',
  'Ibaraki',
  'Yamagata',
  'Saga',
  'Tottori',
  'Yamanashi',
  'Shimane',
] as string[]).forEach((name, i): void =>
  cityNameRegistryInstance.register(new CityName(name, Japanese, i === 0))
);
