"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const Japanese_1 = require("./Japanese");
const CityName_1 = require("@civ-clone/core-civilization/CityName");
const CityNameRegistry_1 = require("@civ-clone/core-civilization/CityNameRegistry");
[
    'Tokyo',
    'Kanagawa',
    'Osaka',
    'Aichi',
    'Hokkaidō',
    'Fukuoka',
    'Hyōgo',
    'Kyoto',
    'Saitama',
    'Hiroshima',
    'Miyagi',
    'Chiba',
    'Niigata',
    'Shizuoka',
    'Okayama',
    'Kumamoto',
    'Kagoshima',
    'Ehime',
    'Tochigi',
    'Ōita',
    'Ishikawa',
    'Nagasaki',
    'Toyama',
    'Kagawa',
    'Gifu',
    'Nagano',
    'Wakayama',
    'Miyazaki',
    'Nara',
    'Fukushima',
    'Kōchi',
    'Gunma',
    'Akita',
    'Shiga',
    'Okinawa',
    'Mie',
    'Aomori',
    'Iwate',
    'Yamaguchi',
    'Fukui',
    'Tokushima',
    'Ibaraki',
    'Yamagata',
    'Saga',
    'Tottori',
    'Yamanashi',
    'Shimane',
].forEach((name, i) => CityNameRegistry_1.instance.register(new CityName_1.default(name, Japanese_1.default, i === 0)));
//# sourceMappingURL=registerCityNames.js.map